
; GAME SECTION 01 :
; 

; FREE SPACE : 0 bytes.


aSegadiscsystem:    dc.b 'SEGADISCSYSTEM  '
aSfcd:              dc.b 'SFCD       '
										dc.b 0
										dc.b 1
										dc.b 0
										dc.b 0
										dc.b 1
aSegaos:            dc.b 'SEGAOS     '
										dc.b 0
										dc.b 1
										dc.b 0
										dc.b 0
										dc.b 0
										dc.l MAIN_CPU_INIT_PRG  ; main 68000 initial program cd offset
										dc.l MAIN_CPU_INIT_PRG  ; main 68000 initial program cd size
										dc.l 0                  ; main 68000 initial program entry offset
										dc.l 0                  ; main 68000 initial program Work RAM size
										dc.l SUB_CPU_INIT_PRG   ; sub 68000 initial program cd offset
										dc.l SUB_CPU_INIT_PRG+$6000
																						; sub 68000 initial program cd size
										dc.l 0                  ; sub 68000 initial program entry offset
										dc.l 0                  ; sub 68000 initial program Work RAM size
a03231995:          dc.b '03231995        '
										dc.b '                '
										dc.b '                '
										dc.b '                '
										dc.b '                '
										dc.b '                '
										dc.b '                '
										dc.b '                '
										dc.b '                '
										dc.b '                '
										dc.b '                '
aSegaMegaDrive:     dc.b 'SEGA MEGA DRIVE '
aCSega:             dc.b '(C)SEGA '
a1995_feb:          dc.b '1995.FEB'
aShiningForceCd:    dc.b 'SHINING FORCE CD'
										dc.b '                '
										dc.b '                '
aShiningForce_0:    dc.b 'SHINING FORCE CD'
										dc.b '                '
										dc.b '                '
aGmMk465600:        dc.b 'GM MK-4656 -00  '
aJ:                 dc.b 'J               '
										dc.b '                '
										dc.b '                '
										dc.b '                '
										dc.b '                '
										dc.b '                '
aE:                 dc.b 'E               '
										dc.b $43 
										dc.b $FA 
										dc.b   0
										dc.b  $A
										dc.b $4E 
										dc.b $B8 
										dc.b   3
										dc.b $64 
										dc.b $60 
										dc.b   0
										dc.b   5
										dc.b $7A 
										dc.b $60 
										dc.b  $F
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b  $C
										dc.b $22 
										dc.b  $E
										dc.b $44 
										dc.b  $E
										dc.b $66 
										dc.b  $E
										dc.b $88 
										dc.b  $E
										dc.b $EE 
										dc.b  $A
										dc.b $AA 
										dc.b   8
										dc.b $88 
										dc.b   4
										dc.b $44 
										dc.b   8
										dc.b $AE 
										dc.b   4
										dc.b $6A 
										dc.b   0
										dc.b  $E
										dc.b   0
										dc.b   8
										dc.b   0
										dc.b   4
										dc.b  $E
										dc.b $20
										dc.b $80 
										dc.b $3F 
										dc.b $80 
										dc.b   5
										dc.b $18
										dc.b $15
										dc.b $1B
										dc.b $26 
										dc.b $39 
										dc.b $36 
										dc.b $38 
										dc.b $45 
										dc.b $17
										dc.b $54 
										dc.b   8
										dc.b $64 
										dc.b   9
										dc.b $72 
										dc.b   0
										dc.b $83 
										dc.b   5
										dc.b $16
										dc.b $86 
										dc.b   3
										dc.b   3
										dc.b $16
										dc.b $3A 
										dc.b $89 
										dc.b   3
										dc.b   2
										dc.b $15
										dc.b $19
										dc.b $26 
										dc.b $3B 
										dc.b $48 
										dc.b $F8 
										dc.b $58 
										dc.b $FA 
										dc.b $67 
										dc.b $7B 
										dc.b $75 
										dc.b $1A
										dc.b $8A 
										dc.b   4
										dc.b  $A
										dc.b $8F 
										dc.b   7
										dc.b $78 
										dc.b $17
										dc.b $79 
										dc.b $37 
										dc.b $7A 
										dc.b $FF
										dc.b   0
										dc.b $23 
										dc.b $AE 
										dc.b $3A 
										dc.b $CF 
										dc.b $2F 
										dc.b $37 
										dc.b $7E 
										dc.b $80 
										dc.b $3F 
										dc.b $ED 
										dc.b $A3 
										dc.b $FF
										dc.b $E0 
										dc.b  $E
										dc.b $FD 
										dc.b $71 
										dc.b $D6 
										dc.b $79 
										dc.b $79 
										dc.b $DB 
										dc.b $DB 
										dc.b $F4 
										dc.b   0
										dc.b $C2 
										dc.b $58 
										dc.b   0
										dc.b $5F 
										dc.b $AB 
										dc.b $BB 
										dc.b $2B 
										dc.b $BF 
										dc.b $C2 
										dc.b $F8 
										dc.b   0
										dc.b $C7 
										dc.b $F5 
										dc.b $B0 
										dc.b $FE 
										dc.b $9A 
										dc.b $85 
										dc.b $FF
										dc.b $F0 
										dc.b $3F 
										dc.b $8D 
										dc.b $BF 
										dc.b $D3 
										dc.b $63 
										dc.b $A0 
										dc.b $BB 
										dc.b $E1 
										dc.b $81 
										dc.b $C3 
										dc.b $E5 
										dc.b $ED 
										dc.b $DF 
										dc.b $AB 
										dc.b $BD 
										dc.b $BB 
										dc.b $BC 
										dc.b $78 
										dc.b $5F 
										dc.b $AF 
										dc.b $C3 
										dc.b $45 
										dc.b $DA 
										dc.b   0
										dc.b $BE 
										dc.b $61 
										dc.b   1
										dc.b $BD 
										dc.b $7D 
										dc.b $61 
										dc.b $42 
										dc.b   0
										dc.b $9D 
										dc.b $68 
										dc.b $17
										dc.b $85 
										dc.b  $D
										dc.b $10
										dc.b $80 
										dc.b $2E 
										dc.b $B1 
										dc.b $FD 
										dc.b $F6 
										dc.b   0
										dc.b   3
										dc.b $E5 
										dc.b $FE 
										dc.b $17
										dc.b $CF 
										dc.b $2E 
										dc.b $D5 
										dc.b $15
										dc.b $77 
										dc.b $69 
										dc.b $AB 
										dc.b $BB 
										dc.b $4D 
										dc.b $5D 
										dc.b $DA 
										dc.b $15
										dc.b   0
										dc.b $18
										dc.b $CD 
										dc.b $D6 
										dc.b $D5 
										dc.b $F3 
										dc.b $CF 
										dc.b $9C 
										dc.b $79 
										dc.b $7E 
										dc.b $11
										dc.b $B7 
										dc.b $C3 
										dc.b   0
										dc.b $38 
										dc.b $64 
										dc.b $B0 
										dc.b   3
										dc.b $97 
										dc.b $FD 
										dc.b $F6 
										dc.b   0
										dc.b   2
										dc.b $84 
										dc.b $11
										dc.b $98 
										dc.b $C8 
										dc.b   0
										dc.b $69 
										dc.b $1D
										dc.b $88 
										dc.b $46 
										dc.b $43 
										dc.b $5F 
										dc.b   0
										dc.b $1D
										dc.b $84 
										dc.b $66 
										dc.b $50 
										dc.b  $B
										dc.b $F9 
										dc.b $EF 
										dc.b $C1 
										dc.b $2C 
										dc.b $21 
										dc.b $DA 
										dc.b $6A 
										dc.b $EE 
										dc.b $DB 
										dc.b $F4 
										dc.b $A8 
										dc.b $C5 
										dc.b $A6 
										dc.b $80 
										dc.b $8A 
										dc.b $9B 
										dc.b $62 
										dc.b $96 
										dc.b $D5 
										dc.b $2C 
										dc.b $59 
										dc.b $6D 
										dc.b $58 
										dc.b $C5 
										dc.b $45 
										dc.b $59 
										dc.b $70 
										dc.b $AC 
										dc.b  $A
										dc.b $17
										dc.b $FF
										dc.b $C6 
										dc.b $13
										dc.b $67 
										dc.b $14
										dc.b $59 
										dc.b $DF 
										dc.b $C7 
										dc.b $E1 
										dc.b $58 
										dc.b   0
										dc.b $17
										dc.b $7F 
										dc.b $EF 
										dc.b   1
										dc.b $A2 
										dc.b $5A 
										dc.b $96 
										dc.b $B8 
										dc.b $7E 
										dc.b $55 
										dc.b $D4 
										dc.b $6B 
										dc.b $7F 
										dc.b $40 
										dc.b   1
										dc.b $F5 
										dc.b $BD 
										dc.b $42 
										dc.b $10
										dc.b $4A 
										dc.b $25 
										dc.b   2
										dc.b   9
										dc.b $44 
										dc.b $EB 
										dc.b $40 
										dc.b $17
										dc.b $EC 
										dc.b $F8 
										dc.b $E7 
										dc.b $E0 
										dc.b   0
										dc.b $58 
										dc.b $44 
										dc.b $A9 
										dc.b $40 
										dc.b $10
										dc.b $8C 
										dc.b $66 
										dc.b $10
										dc.b   4
										dc.b $A7 
										dc.b $FA 
										dc.b $F4 
										dc.b $43 
										dc.b $B4 
										dc.b $D1 
										dc.b $77 
										dc.b $69 
										dc.b $A3 
										dc.b $95 
										dc.b $E5 
										dc.b $72 
										dc.b $A2 
										dc.b $A6 
										dc.b $C8 
										dc.b $BD 
										dc.b $4D 
										dc.b $91 
										dc.b $7A 
										dc.b $9A 
										dc.b $40 
										dc.b   5
										dc.b $FF
										dc.b $35 
										dc.b $1F
										dc.b $93 
										dc.b $BA 
										dc.b $EB 
										dc.b $F5 
										dc.b $E6 
										dc.b $EC 
										dc.b $E2 
										dc.b $82 
										dc.b $CE 
										dc.b $28 
										dc.b $E3 
										dc.b $D6 
										dc.b $3A 
										dc.b $F1 
										dc.b $FB 
										dc.b $6E 
										dc.b $56 
										dc.b $3D 
										dc.b $80 
										dc.b  $A
										dc.b $75 
										dc.b $A0 
										dc.b   0
										dc.b $CC 
										dc.b $64 
										dc.b   2
										dc.b $EA 
										dc.b $16
										dc.b $15
										dc.b $F2 
										dc.b   0
										dc.b $22 
										dc.b $54 
										dc.b $20
										dc.b   2
										dc.b $50 
										dc.b $B8 
										dc.b $D7 
										dc.b $3A 
										dc.b   0
										dc.b $21 
										dc.b  $A
										dc.b $32 
										dc.b   2
										dc.b $14
										dc.b $66 
										dc.b $3B 
										dc.b $BF 
										dc.b $60 
										dc.b   4
										dc.b $20
										dc.b   0
										dc.b $21 
										dc.b $35 
										dc.b $53 
										dc.b $57 
										dc.b $76 
										dc.b $9A 
										dc.b $22 
										dc.b $D3 
										dc.b $44 
										dc.b $2E 
										dc.b $51 
										dc.b $15
										dc.b $36 
										dc.b $45 
										dc.b $EA 
										dc.b $6C 
										dc.b $88 
										dc.b $B6 
										dc.b $6B 
										dc.b $8B 
										dc.b $6E 
										dc.b $DC 
										dc.b $7E 
										dc.b $E4 
										dc.b   0
										dc.b $8A 
										dc.b $5E 
										dc.b $78 
										dc.b $A2 
										dc.b $CE 
										dc.b $28 
										dc.b $2C 
										dc.b $E2 
										dc.b $8C 
										dc.b $7B 
										dc.b $DF 
										dc.b $B0 
										dc.b   3
										dc.b $1E
										dc.b $CD 
										dc.b   0
										dc.b $1A
										dc.b $8D 
										dc.b   0
										dc.b $1B
										dc.b $D6 
										dc.b $89 
										dc.b $44 
										dc.b $27 
										dc.b $74 
										dc.b $F8 
										dc.b $CB 
										dc.b $DF 
										dc.b $7D 
										dc.b $71 
										dc.b $9F 
										dc.b $E7 
										dc.b $80 
										dc.b $D4 
										dc.b $B5 
										dc.b $2F 
										dc.b $31 
										dc.b $D7 
										dc.b $6F 
										dc.b $D7 
										dc.b $66 
										dc.b $11
										dc.b $2D 
										dc.b $4B 
										dc.b $52 
										dc.b $F3 
										dc.b $1D
										dc.b $67 
										dc.b  $F
										dc.b $D7 
										dc.b $EE 
										dc.b $40 
										dc.b   8
										dc.b $D6 
										dc.b $80 
										dc.b   3
										dc.b $4A 
										dc.b $D8 
										dc.b $F8 
										dc.b $C5 
										dc.b $97 
										dc.b   8
										dc.b $AB 
										dc.b $D6 
										dc.b $2C 
										dc.b $B8 
										dc.b $B1 
										dc.b  $B
										dc.b $9F 
										dc.b $DC 
										dc.b $F3 
										dc.b $EE 
										dc.b $D3 
										dc.b $40 
										dc.b   6
										dc.b $B1 
										dc.b $FE 
										dc.b $60 
										dc.b $B3 
										dc.b $8A 
										dc.b $2C 
										dc.b $E2 
										dc.b $A3 
										dc.b $30 
										dc.b $80 
										dc.b $14
										dc.b $80 
										dc.b   3
										dc.b   1
										dc.b $14
										dc.b   4
										dc.b $25 
										dc.b  $E
										dc.b $35 
										dc.b $18
										dc.b $45 
										dc.b $13
										dc.b $56 
										dc.b $39 
										dc.b $67 
										dc.b $79 
										dc.b $75 
										dc.b $14
										dc.b $81 
										dc.b   3
										dc.b   0
										dc.b $16
										dc.b $2F 
										dc.b $27 
										dc.b $78 
										dc.b $82 
										dc.b   4
										dc.b   5
										dc.b $16
										dc.b $36 
										dc.b $83 
										dc.b   5
										dc.b  $C
										dc.b $16
										dc.b $37 
										dc.b $28 
										dc.b $F9 
										dc.b $84 
										dc.b   5
										dc.b $15
										dc.b $17
										dc.b $7B 
										dc.b $85 
										dc.b   5
										dc.b $16
										dc.b $86 
										dc.b   5
										dc.b  $D
										dc.b $16
										dc.b $3A 
										dc.b $87 
										dc.b   5
										dc.b  $F
										dc.b $17
										dc.b $76 
										dc.b $88 
										dc.b   5
										dc.b $10
										dc.b $18
										dc.b $FA 
										dc.b $89 
										dc.b   6
										dc.b $2E 
										dc.b $8A 
										dc.b   6
										dc.b $32 
										dc.b $18
										dc.b $F8 
										dc.b $8B 
										dc.b   5
										dc.b $11
										dc.b $17
										dc.b $7A 
										dc.b $8C 
										dc.b   6
										dc.b $38 
										dc.b $8D 
										dc.b   5
										dc.b $1A
										dc.b $8E 
										dc.b   6
										dc.b $33 
										dc.b $17
										dc.b $77 
										dc.b $8F 
										dc.b   5
										dc.b $12
										dc.b $FF
										dc.b $A5 
										dc.b $28 
										dc.b $9B 
										dc.b $26 
										dc.b $F8 
										dc.b $5A 
										dc.b $F6 
										dc.b $70 
										dc.b $6A 
										dc.b   7
										dc.b $3C 
										dc.b $DE 
										dc.b $E0 
										dc.b $6F 
										dc.b $21 
										dc.b $19
										dc.b $5B 
										dc.b $56 
										dc.b $D5 
										dc.b $77 
										dc.b $FC 
										dc.b $FF
										dc.b $EE 
										dc.b $EF 
										dc.b $CF 
										dc.b $A0 
										dc.b $49 
										dc.b $7F 
										dc.b   4
										dc.b $C8 
										dc.b $60 
										dc.b $10
										dc.b $EF 
										dc.b   7
										dc.b $BD 
										dc.b $FF
										dc.b $D4 
										dc.b $F5 
										dc.b $4F 
										dc.b $99 
										dc.b $F8 
										dc.b $DF 
										dc.b $9B 
										dc.b $D9 
										dc.b $3D 
										dc.b $98 
										dc.b $ED 
										dc.b $A6 
										dc.b $37 
										dc.b $9E 
										dc.b $E6 
										dc.b $D5 
										dc.b $B5 
										dc.b $6C 
										dc.b $58 
										dc.b $59 
										dc.b $FB 
										dc.b $14
										dc.b $6A 
										dc.b $3C 
										dc.b $8C 
										dc.b $55 
										dc.b $18
										dc.b $43 
										dc.b $10
										dc.b $79 
										dc.b $DD 
										dc.b $CC 
										dc.b $E5 
										dc.b $7B 
										dc.b $9B 
										dc.b $B4 
										dc.b $6B 
										dc.b $6C 
										dc.b $F5 
										dc.b $6E 
										dc.b $21 
										dc.b $61 
										dc.b $F2 
										dc.b $1E
										dc.b $8C 
										dc.b $73 
										dc.b $1B
										dc.b $8E 
										dc.b $D4 
										dc.b $A3 
										dc.b $84 
										dc.b $DB 
										dc.b $8E 
										dc.b $CC 
										dc.b $20
										dc.b $FE 
										dc.b $D5 
										dc.b $AC 
										dc.b $D8 
										dc.b $F8 
										dc.b $3B 
										dc.b $CE 
										dc.b $F4 
										dc.b $13
										dc.b  $A
										dc.b $9B 
										dc.b $65 
										dc.b $5D 
										dc.b $93 
										dc.b $6C 
										dc.b $F9 
										dc.b $A9 
										dc.b $CD 
										dc.b $D6 
										dc.b $AF 
										dc.b $78 
										dc.b $22 
										dc.b $BF 
										dc.b $5F 
										dc.b $99 
										dc.b $1F
										dc.b   9
										dc.b $1C
										dc.b $BD 
										dc.b $4D 
										dc.b $A3 
										dc.b $9D 
										dc.b $35 
										dc.b $F7 
										dc.b $E3 
										dc.b $F3 
										dc.b $BD 
										dc.b $3B 
										dc.b $D6 
										dc.b $9A 
										dc.b $F4 
										dc.b $89 
										dc.b $E8 
										dc.b $38 
										dc.b $1D
										dc.b $3B 
										dc.b $AE 
										dc.b   6
										dc.b $47 
										dc.b $EB 
										dc.b $F5 
										dc.b $95 
										dc.b $9F 
										dc.b $BB 
										dc.b  $B
										dc.b $8B 
										dc.b   7
										dc.b $E5 
										dc.b $7F 
										dc.b $33 
										dc.b $F3 
										dc.b $D4 
										dc.b $12
										dc.b $2C 
										dc.b $B7 
										dc.b $68 
										dc.b $78 
										dc.b $83 
										dc.b $50 
										dc.b $41 
										dc.b $ED 
										dc.b $F3 
										dc.b $98 
										dc.b $8E 
										dc.b $B8 
										dc.b $5D 
										dc.b $28 
										dc.b $8E 
										dc.b $5E 
										dc.b $26 
										dc.b  $E
										dc.b $72 
										dc.b   5
										dc.b $4E 
										dc.b $64 
										dc.b $67 
										dc.b $67 
										dc.b $4B 
										dc.b $BD 
										dc.b $B0 
										dc.b $25 
										dc.b $97 
										dc.b $EC 
										dc.b $8E 
										dc.b $AC 
										dc.b $B3 
										dc.b $BF 
										dc.b $98 
										dc.b $AF 
										dc.b $C7 
										dc.b $AF 
										dc.b $84 
										dc.b $CB 
										dc.b $86 
										dc.b $10
										dc.b $8F 
										dc.b $39 
										dc.b $85 
										dc.b $20
										dc.b $88 
										dc.b $77 
										dc.b  $A
										dc.b $D2 
										dc.b $DC 
										dc.b $DD 
										dc.b $74 
										dc.b $91 
										dc.b $A2 
										dc.b $50 
										dc.b $2A 
										dc.b $E7 
										dc.b $C0 
										dc.b $C2 
										dc.b $EC 
										dc.b $69 
										dc.b $F9 
										dc.b $C7 
										dc.b $F5 
										dc.b $51 
										dc.b $BA 
										dc.b $D1 
										dc.b $BB 
										dc.b  $F
										dc.b $32 
										dc.b $89 
										dc.b $BE 
										dc.b   0
										dc.b $B0 
										dc.b $BE 
										dc.b $17
										dc.b   3
										dc.b $B9 
										dc.b $90 
										dc.b $46 
										dc.b   4
										dc.b $E9 
										dc.b $77 
										dc.b $3B 
										dc.b   4
										dc.b $63 
										dc.b $95 
										dc.b $2E 
										dc.b $31 
										dc.b $73 
										dc.b $DB 
										dc.b $15
										dc.b $B9 
										dc.b $CA 
										dc.b $8B 
										dc.b $3F 
										dc.b $D1 
										dc.b $52 
										dc.b $94 
										dc.b $A5 
										dc.b $3C 
										dc.b $FE 
										dc.b $75 
										dc.b $ED 
										dc.b $5C 
										dc.b  $C
										dc.b $86 
										dc.b $5C 
										dc.b $C9 
										dc.b $AE 
										dc.b $D0 
										dc.b $B3 
										dc.b $66 
										dc.b $C6 
										dc.b $B2 
										dc.b   9
										dc.b $F9 
										dc.b $DD 
										dc.b $86 
										dc.b $49 
										dc.b $7F 
										dc.b $3F 
										dc.b $DC 
										dc.b $5F 
										dc.b $77 
										dc.b $63 
										dc.b $2B 
										dc.b $CC 
										dc.b $1A
										dc.b $92 
										dc.b $D7 
										dc.b   3
										dc.b $BB 
										dc.b $D3 
										dc.b $F3 
										dc.b $F9 
										dc.b $89 
										dc.b $5D 
										dc.b $A1 
										dc.b $97 
										dc.b $AF 
										dc.b $86 
										dc.b $11
										dc.b $1F
										dc.b $E8 
										dc.b $C4 
										dc.b $65 
										dc.b $81 
										dc.b $C3 
										dc.b $DB 
										dc.b $FB 
										dc.b $CD 
										dc.b $52 
										dc.b $94 
										dc.b $A6 
										dc.b $A9 
										dc.b $4F 
										dc.b $3A 
										dc.b $F3 
										dc.b $5F 
										dc.b $D2 
										dc.b $FB 
										dc.b $DC 
										dc.b $7C 
										dc.b $87 
										dc.b $A3 
										dc.b $1C
										dc.b $C6 
										dc.b $E3 
										dc.b $B5 
										dc.b $1C
										dc.b $29 
										dc.b $36 
										dc.b $E3 
										dc.b $B3 
										dc.b   8
										dc.b $3F 
										dc.b $B5 
										dc.b $6B 
										dc.b $36 
										dc.b $3E 
										dc.b  $E
										dc.b $F3 
										dc.b $BD 
										dc.b   4
										dc.b $C2 
										dc.b $D6 
										dc.b $DF 
										dc.b $D2 
										dc.b $4D 
										dc.b $A7 
										dc.b $24 
										dc.b $5A 
										dc.b $63 
										dc.b $3A 
										dc.b $FD 
										dc.b $45 
										dc.b $5B 
										dc.b $FA 
										dc.b $CA 
										dc.b $A6 
										dc.b $49 
										dc.b $EE 
										dc.b $C2 
										dc.b $E9 
										dc.b $5F 
										dc.b $F9 
										dc.b $5F 
										dc.b $CC 
										dc.b $B2 
										dc.b $43 
										dc.b $A8 
										dc.b $24 
										dc.b $6E 
										dc.b $1D
										dc.b $A1 
										dc.b $79 
										dc.b $C9 
										dc.b $A8 
										dc.b $20
										dc.b $F0 
										dc.b $5F 
										dc.b $36 
										dc.b $9E 
										dc.b $17
										dc.b $88 
										dc.b $5C 
										dc.b $D9 
										dc.b $47 
										dc.b $24 
										dc.b $AC 
										dc.b $C4 
										dc.b $B0 
										dc.b $A7 
										dc.b $B8 
										dc.b $9E 
										dc.b $61 
										dc.b $EB 
										dc.b $8C 
										dc.b $E4 
										dc.b $9F 
										dc.b $A2 
										dc.b $22 
										dc.b $3C 
										dc.b $D7 
										dc.b $CF 
										dc.b $D6 
										dc.b $51 
										dc.b $AA 
										dc.b $E9 
										dc.b $70 
										dc.b $F3 
										dc.b $25 
										dc.b $37 
										dc.b $C0 
										dc.b $16
										dc.b $17
										dc.b $C2 
										dc.b $E0 
										dc.b $77 
										dc.b $32 
										dc.b   8
										dc.b $C0 
										dc.b $9D 
										dc.b $2E 
										dc.b $E7 
										dc.b $60 
										dc.b $8C 
										dc.b $72 
										dc.b $A5 
										dc.b $C6 
										dc.b $2E 
										dc.b   0
										dc.b   0
										dc.b   6
										dc.b   3
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   1
										dc.b   5
										dc.b $10
										dc.b $12
										dc.b $C2 
										dc.b   4
										dc.b $88 
										dc.b $50 
										dc.b $11
										dc.b   4
										dc.b $80 
										dc.b $14
										dc.b   5
										dc.b $10
										dc.b $9A 
										dc.b $21 
										dc.b $54 
										dc.b $42 
										dc.b $60 
										dc.b   5
										dc.b   5
										dc.b   1
										dc.b $34 
										dc.b $38 
										dc.b $11
										dc.b $40 
										dc.b $51 
										dc.b $11
										dc.b $81 
										dc.b $14
										dc.b   4
										dc.b   1
										dc.b $10
										dc.b $20
										dc.b $C5 
										dc.b   5
										dc.b   1
										dc.b $5C 
										dc.b $58 
										dc.b   2
										dc.b $20
										dc.b $40 
										dc.b $1F
										dc.b   2
										dc.b   0
										dc.b $88 
										dc.b $10
										dc.b   7
										dc.b $C3 
										dc.b $80 
										dc.b $C8 
										dc.b   4
										dc.b   1
										dc.b $A1 
										dc.b $38 
										dc.b $B4 
										dc.b $94 
										dc.b   1
										dc.b   0
										dc.b $AC 
										dc.b $58 
										dc.b  $E
										dc.b $20
										dc.b $40 
										dc.b $1A
										dc.b $13
										dc.b $93 
										dc.b $B1 
										dc.b $A9 
										dc.b $A8 
										dc.b $1C
										dc.b $5D 
										dc.b $8D 
										dc.b $42 
										dc.b $E2 
										dc.b $68 
										dc.b $6C 
										dc.b  $F
										dc.b $F0 
										dc.b   5
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b $39 
										dc.b  $A
										dc.b $41 
										dc.b   6
										dc.b   1
										dc.b $81 
										dc.b $80 
										dc.b $90 
										dc.b $29 
										dc.b $AF 
										dc.b $F8 
aProducedByOrUnde:  dc.b 'PRODUCED BY OR UNDER LICENSE'
										dc.b   0
										dc.b   0
aFromSegaEnterpri:  dc.b ' FROM SEGA ENTERPRISES, LTD.'
										dc.b $FF
										dc.b $14
										dc.b $11
										dc.b   8
										dc.b  $D
										dc.b $17
										dc.b $11
										dc.b   0
										dc.b  $D
										dc.b $14
										dc.b $11
										dc.b $14
										dc.b $11
										dc.b $90 
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b $1C
										dc.b $14
										dc.b $11
										dc.b $80 
										dc.b $80 
										dc.b $80 
										dc.b $1D
										dc.b $11
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b $AE 
										dc.b $11
										dc.b   7
										dc.b   0
										dc.b   1
										dc.b   0
										dc.b $AD 
										dc.b $11
										dc.b   0
										dc.b   0
										dc.b $3F 
										dc.b $11
										dc.b   0
										dc.b  $B
										dc.b $48 
										dc.b $11
										dc.b   0
										dc.b  $B
										dc.b $66 
										dc.b $11
										dc.b   0
										dc.b  $B
										dc.b $84 
										dc.b $11
										dc.b   0
										dc.b  $B
										dc.b $93 
										dc.b $11
										dc.b   0
										dc.b  $B
										dc.b $A2 
										dc.b $11
										dc.b   0
										dc.b  $B
										dc.b $EF 
										dc.b   1
										dc.b $E0 
										dc.b $80 
										dc.b $80 
										dc.b  $A
										dc.b $C9 
										dc.b  $C
										dc.b $F2 
										dc.b $80 
										dc.b   5
										dc.b $80 
										dc.b $39 
										dc.b $80 
										dc.b   5
										dc.b $80 
										dc.b  $C
										dc.b $EF 
										dc.b   0
										dc.b $F0 
										dc.b  $A
										dc.b   1
										dc.b   2
										dc.b   8
										dc.b $A9 
										dc.b $1F
										dc.b $80 
										dc.b   1
										dc.b $A5 
										dc.b $40 
										dc.b $E7 
										dc.b $A5 
										dc.b   2
										dc.b $F7 
										dc.b   0
										dc.b   8
										dc.b $5D 
										dc.b $11
										dc.b $F2 
										dc.b $80 
										dc.b   5
										dc.b $80 
										dc.b $39 
										dc.b $80 
										dc.b   5
										dc.b $80 
										dc.b  $C
										dc.b $EF 
										dc.b   0
										dc.b $F0 
										dc.b  $A
										dc.b   1
										dc.b   2
										dc.b   8
										dc.b $B8 
										dc.b $1F
										dc.b $80 
										dc.b   1
										dc.b $B5 
										dc.b $40 
										dc.b $E7 
										dc.b $B5 
										dc.b   2
										dc.b $F7 
										dc.b   0
										dc.b   8
										dc.b $7B 
										dc.b $11
										dc.b $F2 
										dc.b $EF 
										dc.b   1
										dc.b $E0 
										dc.b $80 
										dc.b $80 
										dc.b   5
										dc.b $C4 
										dc.b  $C
										dc.b $E0 
										dc.b $40 
										dc.b $80 
										dc.b   5
										dc.b $C4 
										dc.b $39 
										dc.b $F2 
										dc.b $EF 
										dc.b   1
										dc.b $E0 
										dc.b $80 
										dc.b $80 
										dc.b  $A
										dc.b $80 
										dc.b   7
										dc.b $E0 
										dc.b $40 
										dc.b $80 
										dc.b  $A
										dc.b $C9 
										dc.b $34 
										dc.b $F2 
										dc.b $EF 
										dc.b   1
										dc.b $E0 
										dc.b $80 
										dc.b $C1 
										dc.b $12
										dc.b $E0 
										dc.b $40 
										dc.b $C1 
										dc.b $3F 
										dc.b $F2 
										dc.b $F2 
										dc.b $32 
										dc.b   1
										dc.b   1
										dc.b   1
										dc.b   1
										dc.b $3F 
										dc.b $1F
										dc.b $1F
										dc.b $1F
										dc.b $19
										dc.b   6
										dc.b   4
										dc.b   7
										dc.b   8
										dc.b   5
										dc.b   5
										dc.b   4
										dc.b $19
										dc.b $19
										dc.b $19
										dc.b $19
										dc.b $11
										dc.b $89 
										dc.b $18
										dc.b $87 
										dc.b   4
										dc.b $37 
										dc.b $72 
										dc.b $77 
										dc.b $49 
										dc.b $1F
										dc.b $1F
										dc.b $1F
										dc.b $1F
										dc.b   7
										dc.b  $A
										dc.b   7
										dc.b  $D
										dc.b   0
										dc.b  $B
										dc.b   0
										dc.b  $B
										dc.b $1F
										dc.b  $F
										dc.b $1F
										dc.b  $F
										dc.b $23 
										dc.b $80 
										dc.b $23 
										dc.b $80 
										dc.b $46 
										dc.b $FC 
										dc.b $27 
										dc.b   0
										dc.b $41 
										dc.b $FA 
										dc.b   0
										dc.b $2E 
										dc.b $4E 
										dc.b $71 
										dc.b $43 
										dc.b $F9 
										dc.b   0
										dc.b $FF
										dc.b $80 
										dc.b   0
										dc.b $32 
										dc.b $3C 
										dc.b   0
										dc.b $12
										dc.b $22 
										dc.b $D8 
										dc.b $22 
										dc.b $D8 
										dc.b $22 
										dc.b $D8 
										dc.b $22 
										dc.b $D8 
										dc.b $51 
										dc.b $C9 
										dc.b $FF
										dc.b $F6 
										dc.b $43 
										dc.b $F9 
										dc.b   0
										dc.b $FF
										dc.b $80 
										dc.b   0
										dc.b $4E 
										dc.b $B8 
										dc.b   3
										dc.b $68 
										dc.b $46 
										dc.b $FC 
										dc.b $25 
										dc.b   0
										dc.b $4E 
										dc.b $F9 
										dc.b   0
										dc.b $FF
										dc.b $80 
										dc.b  $A
										dc.b   8
										dc.b $F9 
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b $A1 
										dc.b $20
										dc.b   0
										dc.b $4E 
										dc.b $73 
										dc.b $61 
										dc.b   0
										dc.b   0
										dc.b $2C 
										dc.b $61 
										dc.b   0
										dc.b   0
										dc.b $7C 
										dc.b $46 
										dc.b $FC 
										dc.b $25 
										dc.b   0
										dc.b $41 
										dc.b $F9 
										dc.b   0
										dc.b $23 
										dc.b $80 
										dc.b   0
										dc.b $43 
										dc.b $F9 
										dc.b   0
										dc.b $FF
										dc.b   0
										dc.b   0
										dc.b $32 
										dc.b $3C 
										dc.b   4
										dc.b   0
										dc.b $22 
										dc.b $D8 
										dc.b $22 
										dc.b $D8 
										dc.b $22 
										dc.b $D8 
										dc.b $22 
										dc.b $D8 
										dc.b $51 
										dc.b $C9 
										dc.b $FF
										dc.b $F6 
										dc.b $4E 
										dc.b $F9 
										dc.b   0
										dc.b $FF
										dc.b   0
										dc.b   0
										dc.b   8
										dc.b $39 
										dc.b   0
										dc.b   4
										dc.b   0
										dc.b $A1 
										dc.b $20
										dc.b $2E 
										dc.b $67 
										dc.b $F6 
										dc.b   8
										dc.b $F9 
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b $A1 
MAIN_CPU_INIT_PRG:  incbin "sector0001-maincpu-initprg.bin"
SUB_CPU_INIT_PRG:   incbin "sector0002-000F-subcpu-initprg.bin"
										incbin "sector0010-0016-filesystem-header.bin"
										incbin "filesystem/MC_MSG02.ROM"
										incbin "filesystem/CPY.TXT"
										align $800
										incbin "filesystem/ABS.TXT"
																						; ABS.TXT
										align $800
										incbin "filesystem/BIB.TXT"
										align $800
										incbin "filesystem/AT.BIN"
																						; AT.BIN
										incbin "filesystem/SFEOPEN.P32"
										align $800
										incbin "filesystem/SFEOPENU.P32"
										align $800
										incbin "filesystem/SFEEND1.P32"
										align $800
										incbin "filesystem/SFEEND1U.P32"
										align $800
										incbin "filesystem/SFEEND2.P32"
										align $800
										incbin "filesystem/SFEEND2U.P32"
										align $800
										incbin "filesystem/SFEEND3.P32"
										align $800
										incbin "filesystem/SFEEND3U.P32"
										align $800
										incbin "filesystem/SFE_PCM.BIN"
										incbin "filesystem/SFELOGO.X"
										incbin "filesystem/SFEOPEN.X"
										incbin "filesystem/SFEMAIN.X"
										incbin "filesystem/BANKD1F.X"
										incbin "filesystem/SFEEND1.X"
										incbin "filesystem/SFEEND2.X"
										incbin "filesystem/SFEEND3.X"
										incbin "filesystem/SFEEND4.X"
										incbin "filesystem/BANKD00.X"
										incbin "filesystem/BANKD01.X"
										incbin "filesystem/BANKD02.X"
										incbin "filesystem/BANKD03.X"
										incbin "filesystem/BANKD04.X"
										incbin "filesystem/BANKD05.X"
										incbin "filesystem/BANKD06.X"
										incbin "filesystem/BANKD07.X"
										incbin "filesystem/BANKD08.X"
										incbin "filesystem/BANKD09.X"
										incbin "filesystem/BANKD0A.X"
										incbin "filesystem/BANKD0B.X"
										incbin "filesystem/BANKD0C.X"
										incbin "filesystem/BANKD0D.X"
										incbin "filesystem/BANKD0E.X"
										incbin "filesystem/BANKD0F.X"
										incbin "filesystem/BANKD10.X"
										incbin "filesystem/BANKD11.X"
										incbin "filesystem/BANKD12.X"
										incbin "filesystem/BANKD13.X"
										incbin "filesystem/BANKD14.X"
										incbin "filesystem/BANKD15.X"
										incbin "filesystem/BANKD16.X"
										incbin "filesystem/BANKD17.X"
										align $800
										incbin "filesystem/BANKD18.X"
										align $800
										incbin "filesystem/BANKD19.X"
										align $800
										incbin "filesystem/BANKD1A.X"
										align $800
										incbin "filesystem/BANKD1B.X"
										align $800
										incbin "filesystem/BANKD1C.X"
										align $800
										incbin "filesystem/BANKD1D.X"
										align $800
										incbin "filesystem/BANKD1E.X"
										align $800
										incbin "filesystem/BANKD20.X"
										incbin "filesystem/BANKD21.X"
										incbin "filesystem/BANKD22.X"
										incbin "filesystem/BANKD23.X"
										incbin "filesystem/BANKD24.X"
										incbin "filesystem/BANKD25.X"
										incbin "filesystem/BANKD26.X"
										incbin "filesystem/BANKD27.X"
										incbin "filesystem/BANKD28.X"
										incbin "filesystem/BANKD29.X"
										incbin "filesystem/BANKD2A.X"
										incbin "filesystem/BANKD2B.X"
										incbin "filesystem/BANKD2C.X"
										incbin "filesystem/BANKD2D.X"
										incbin "filesystem/BANKD2E.X"
										incbin "filesystem/BANKD2F.X"
										incbin "filesystem/BANKD30.X"
										incbin "filesystem/BANKD31.X"
										incbin "filesystem/BANKD32.X"
										incbin "filesystem/BANKD33.X"
										incbin "filesystem/BANKD34.X"
										incbin "filesystem/BANKD35.X"
										incbin "filesystem/BANKD36.X"
										incbin "filesystem/BANKD37.X"
										incbin "filesystem/BANKD38.X"
										incbin "filesystem/BANKD39.X"
										incbin "filesystem/BANKD3A.X"
										incbin "filesystem/BANKD3B.X"
										incbin "filesystem/BANKD3C.X"
										align $800
										incbin "filesystem/BANKD3D.X"
										align $800
										incbin "filesystem/BANKD3E.X"
										align $800
										incbin "filesystem/BANKD3F.X"
										align $800
										incbin "filesystem/BANKD40.X"
										incbin "filesystem/BANKD41.X"
										incbin "filesystem/BANKD42.X"
										incbin "filesystem/BANKD43.X"
										incbin "filesystem/BANKD44.X"
										incbin "filesystem/BANKD45.X"
										incbin "filesystem/BANKD46.X"
										incbin "filesystem/BANKD47.X"
										incbin "filesystem/BANKD48.X"
										align $10000
										align $100000
										align $40000
										align $8000
										align $4000
										align $2000
										align $1000
